version: "3.5"

services:
  flask-api:
    build:
      context: ./api
    restart: unless-stopped
    container_name: flask-api
    image: example-flask-api
    ports:
      - "5000:5000"
    networks:
      example-network:
        ipv4_address: 172.16.238.10

  demo-prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: demo-prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      example-network:
        ipv4_address: 172.16.238.11

  demo-grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: demo-grafana
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/config.ini:/etc/grafana/grafana.ini
      - ./monitoring/grafana/datasource.yml:/etc/grafana/provisioning/datasources/default.yml
      - ./monitoring/grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/default.yml
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      example-network:
        ipv4_address: 172.16.238.12

networks:
  example-network:
    name: example-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24